### ISSUE TITLE
Questions about IMessage interface

### ISSUE THREAD

**Issue by gforcada** [tisto/plonesocial.messaging#5]
Some questions here:
- do we need to keep both `receiver` and `sender` as the parent of a `Message` already provides us with who the conversation is, and the parent of `Conversation` already told us who's the inbox member, having only one field `sent` to be True when the inbox owner is the one that sent that particular message and False when the inbox owner is the one getting the message would be enough, don't you thing?

Then we just need to create a couple of properties get_sender and get_receiver that will check that flag and use the **parent** pointers to get that information.

Storage-wise will save quite a lot of data, but also will make future renaming operations (a member changes it's username) far more straightforward.
- something along the previous would be for the `new` property too. As we only want to keep information about that on the Conversation level, maybe is enough to keep the counter at the Conversation object and leave the message without any kind of information regarding its status. Once a member opens a conversation the whole thread will be marked as read, so if we keep the counter on the Conversation, that will be just zeroing that counter and not having to go through the messages. So `Conversation.mark_read` will be way simpler
- the `deleted` property is a leftover from a previous implementation? Maybe the one we thought about keeping messages in a single place and thus having to keep the message if only one of the members deleted it?

**Comment by csenger** [comment]
I can change the stored information into computed properties.

> Some questions here:
> - do we need to keep both receiver and sender as the parent of a Message already provides us with who the conversation is, and the parent of Conversation already told us who's the inbox member, having only one field sent to be True when the inbox owner is the one that sent that particular message and False when the inbox owner is the one getting the message would be enough, don't you thing?
>   
>   Then we just need to create a couple of properties get_sender and get_receiver that will check that flag and use the parent pointers to get that information.
>   
>     Storage-wise will save quite a lot of data, but also will make future renaming operations (a member changes it's username) far more straightforward.

I found the explicit storage easier to grok and didn't expect that users can change their userid. But I can change .sender and .reciver into @property(s) and store only a boolean.

> - something along the previous would be for the new property too. As we only want to keep information about that on the Conversation level, maybe is enough to keep the counter at the Conversation object and leave the message without any kind of information regarding its status. Once a member opens a conversation the whole thread will be marked as read, so if we keep the counter on the Conversation, that will be just zeroing that counter and not having to go through the messages. So Conversation.mark_read will be way simpler

Maybe. The spec says:

>  once a member in that list is selected, all, if any, messages pending to be read are 
>  marked as read, without any option to allow the member to mark them back as unread

I thought that was an information required to highlight unread messages when you display the conversation. Usability wise I'd find that good, 
I don't think it's overly complicated though a flag on the conversation would have been easier to implement. Should I replace it?

> -  the deleted property is a leftover from a previous implementation? Maybe the one we thought about keeping messages in a single place and thus having to keep the message if only one of the members deleted it?

Yes, I'll remove it. The implementation actually deletes the object.
