### ISSUE TITLE
Question about the IMessagingLocator

### ISSUE THREAD

**Issue by gforcada** [tisto/plonesocial.messaging#7]
That's the part I'm quite lost, as I never really understood how they work exactly (plone/zope tools and utilities I mean) so probably the following is just plain stupid, but anyway:

Would it make sense to rename it to IMessagingTool? I don't get what should I be getting by a tool called locator (sorry a bit of bikeshedding).

As far as I can see, this tool is only to get the Inboxes object, so my question is: would it be possible to just get rid of the Inboxes class and from the messaging tool get directly inbox objects? I got a bit confused from time to time while reviewing the code about Inbox and Inboxes. Maybe renaming Inbox to MemberInbox and keeping Inboxes or even renaming Inboxes to MessagingStorage?

Still my brain can picture more easily a `Tool -> Inbox -> Conversation -> Message` chain.

**Comment by csenger** [comment]
I added the tool for some reasons:
- You have it in content space and can delete it through the ZMI. I'd prefer a local utility theoretically, but they get annoying if they break which frustrates users.
- If we go with a seperate storage, we need a mount point. Of cause local utilities are also stored somewhere, I guess it is hidden in some kind of BTree in an annotation in the side managers annotation. I'd did not want to mess with that.
- I did the same as plonesocial.microblog, except of the locator.

The IMessagingLocator is there to have a simple way to switch the storage to something else. If we switch out the ZODB storage with a RDBMS, we only need to override the utility. We don't need to write a plone tool and install it in content space. However I'm not entirely happy with that too.

It's a good Idea to rename 'Inboxes' to MessagingStorage.
